### ISSUE TITLE
Plugin conflicts with Events Manager and WPML plugin working together

### ISSUE THREAD

**Issue by mike-leber** [andyplak/events-manager-tax-per-event#5]
Hi Andy,

I use Events Manager together with WPML for multi-language purposes. Now, when I started trying your plugin, which could be an awesome add-on for my needs to run events in different countries with different VAT conditions, I figured out via WPML support, that it would hinder certain elements of Events Manager (booking form / table headers) to display in their localized version.

These guys traced this down quite quickly, what I would have not found myself. And they would be happy to support making your code compatible with WPML, which might be the most wide-spread plugin for multi-lingual installations in Wordpress today.

They will also contact you via your Github / web presence. So the only question I had, if you could at least have a look into this?

cheers,
Mike

**Comment by andyplak** [comment]
Hi Mike,

No problem looking into that. There are various hooks that can be utilized to modify the booking form table columns. I think Events Manager recently underwent some changes to bring it inline with the latest WPML changes. I'll await more detail from the WPML chaps, but imagine it will be pretty straight forward.

**Comment by mike-leber** [comment]
Hi Andy,
Could you have a look into design options already?
cheers

**Comment by andyplak** [comment]
Hi Mike,
. 
I've not had any more details as to where the problem lies. It might be as simple as making all the text strings translatable (something that wasn't required for who this was knocked up for originally).

I can setup WPML and have a test myself, however if you can show me where you saw problems (any errors or untranslated text seen in your browser) then that will save me time understanding/replicating it.

I'll be away for two weeks as of this Friday so it won't be until the 2nd week of February before I can take a look.

**Comment by mike-leber** [comment]
Hi Andy,

Sorry for my late reply. Yes, it is about the header strings of the booking table, which the code here seems to have hardcoded. Hence, when activating this plugin, they will be overwritten in English language, despite the (WMPL recognized) language of a given page.

If you check this event page: http://agileexperts.at/de/trainings/kanban-training-wien-03-2016 there is a booking table on the bottom of the page. The whole page is in German, Hence the header strings are displayed in German. If I would enable the plugin here, they'd be overwritten in English.

**Comment by andyplak** [comment]
@mike-leber I've made some changes to the plugin so the text strings are translatable. You've now got two choices to translate the text. Either add translations directly to the de_AT.po file and then generate a .mo file so that the translations are detected by WordPress, or use the WPML to translate the plugin strings: https://wpml.org/documentation/getting-started-guide/theme-localization/

The former method is preferred (by me at least), as any translation you make can be fed back into this plugin. If the creation of .po and .mo files is a bit alien to you, all you'd need to do is add translation strings to [this file](https://github.com/andyplak/events-manager-tax-per-event/blob/master/languages/em-tax-per-event-de_AT.po) and I can then generate the .mo file for you.

i.e. In line 113, you'd add the German translation for Ticket Type: https://github.com/andyplak/events-manager-tax-per-event/blob/master/languages/em-tax-per-event-de_AT.po#L112-L113

**Comment by mike-leber** [comment]
Thanks a lot @andyplak! It works and I made the translations. By the way, Austrian borrows from German up to 100%, so I went with the .DE-Versions. If you want me to upload the file, please let me know (push upload is prohibited)

**Comment by andyplak** [comment]
@mike-leber great, glad to hear it. I've added you as a collaborator so you should be able to push the files now. If its easier, send me an email via http://www.andyplace.co.uk/contact/. I'll drop you an email and you can then reply with the files attached.
